name: TOC Generator
on:
  push:
    branches:
      - main

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest

    steps:
      - uses: technote-space/toc-generator@v4.0.0

        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_PR: true
          TARGET_PATHS: "README*.md,CONTRIBUTING*.md"
          FOLDING: true
          COMMIT_MESSAGE: '(docs) Update TOC'
          PR_TITLE: '(docs) Update TOC (${PR_MERGE_REF})'
