name: Update Packages
on:
  push:
    branches: ["main"]
    paths: ["automatic/**", "!**/*.md"]
  #--- TODO: For now also enable manual runs
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  update-all:
    name: Update All Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell#installing-dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module au, wormies-au-helpers
      - name: Update Packages
        shell: pwsh
        run: |
          ./update_all.ps1
        env:
          au_push: "true"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update packages"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}  # Push to the same branch that triggered the workflow
          github_user_reponame: ${{ github.repository }}
          github_api_key: ${{ secrets.GITHUB_TOKEN }}
          gist_id: 566db9ad4a81bc3d4d392cd7ec8b4ade
          #gist_id_test: 566db9ad4a81bc3d4d392cd7ec8b4ade
