name: Update Packages
on:
  # push:
  #   branches:
  #     - main
  #--- TODO: For now also enable manual runs
  workflow_dispatch:

jobs:
  update-all:
    name: Update All Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Packages
        shell: pwsh
        run: |
          ./update-all.ps1
        env:
          au_push: "true"
