name: Update Packages
on:
  # push:
  #   branches:
  #     - main
  #--- TODO: For now also enable manual runs
  workflow_dispatch:

jobs:
  update-all:
    name: Update All Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell#installing-dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module au, wormies-au-helpers
      - name: Update Packages
        shell: pwsh
        run: |
          ./update_all.ps1
        env:
          au_push: "true"
          github_api_key: ${{ secrets.GITHUB_TOKEN }}
